version: '3.8'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testParking1
      MYSQL_USER: root
    networks:
      - spring-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 20s
      timeout: 10s
      retries: 10



#  frontend:
#    image: firassaafi/firassaafidocker:myfront
#    ports:
#      - "4200:80"
#    depends_on:
#      - backend

  backend:
    image: firassaafi/firassaafidocker:myback
    ports:
      - "9300:9300"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3307/testParking1?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_PORT: 9300
    networks:
      - spring-net


networks:
  spring-net:
    name: spring-net
    driver: bridge
