version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testParking1
    ports:
      - "3306:3306"
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql"]
      interval: 20s
      timeout: 10s
      retries: 10

  backend:
    image: nawreslakhal/devops:backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/testParking1?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_PORT: 9200
    ports:
      - "9200:9200"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - my-network

  frontend:
    image: nawreslakhal/devops:frontend
    ports:
      - "4200:80"
    networks:
      - my-network

  mysql-exporter:
    image: prom/mysqld-exporter
    environment:
      - MYSQL_CONFIG_FILE=/root/.my.cnf  # Set the environment variable
    ports:
      - "9104:9104"  # MySQL Exporter
    networks:
      - my-network
    volumes:
      - ./mysql-exporter/.my.cnf:/etc/mysql/.my.cnf 
    depends_on:
      - mysql  

networks:
  my-network:
    driver: bridge
