version: '3.8'  # Define the version of Docker Compose

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testParking1
    ports:
      - "3306:3306"
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql"]
      interval: 20s
      timeout: 10s
      retries: 10

  backend:
    image: salsabilhamraoui510802/salsabylhamraoui:back  # Use the correct image name and tag
    container_name: backend-container  # Corrected container name for consistency
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/testParking1?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_PORT: 9200
    ports:
      - "9200:9200"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - my-network

  frontend:
    image: salsabilhamraoui510802/salsabylhamraoui:latest  # Specify the latest tag or whichever you prefer
    container_name: frontend-container  # Consistent naming
    ports:
      - "4200:80"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
