services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testParking1
    ports:
      - "3306:3306"
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 10s
      retries: 10

  backend:
    image: yosserchb123/imagebackfinal
    container_name: backend-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/testParking1?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_PORT: 9200
    ports:
      - "9200:9200"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - my-network

  frontend:
    image: yosserchb123/frontimage
    container_name: frontend-container
    ports:
      - "4200:80"
    networks:
      - my-network

  mysql-exporter:
    image: prom/mysqld-exporter
    container_name: mysql-exporter
    environment:
      DATA_SOURCE_NAME: "root:root@(mysql:3306)/"
    ports:
      - "9104:9104"
    networks:
      - my-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - my-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
