version: '3.8'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testParking1
      MYSQL_USER: root
    networks:
      - spring-net




#  frontend:
#    image: firassaafi/firassaafidocker:myfront
#    ports:
#      - "4200:80"
#    depends_on:
#      - backend

  backend:
    image: firassaafi/firassaafidocker:myback
    ports:
      - "9200:9200"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: testParking1
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - spring-net


networks:
  spring-net:
    name: spring-net
    driver: bridge
