

services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testParking1
    ports:
      - "3306:3306"
    networks:
      - my-network
    volumes :
      - db:/var/lib/mysql

  backend:
    depends_on:
      - mysql

    image: 22chaima22/vagrantbackend
    restart: on-failure
    container_name: backend-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/testParking1?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_PORT: 9200
    ports:
      - "9200:9200"


    networks:
      - my-network

  frontend:
    image: 22chaima22/vagrantfront
    container_name: frontend-container
    ports:
      - "4200:80"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
