version: '3.8'

services:
  mysql:
    image: firassaafi/firassaafidocker:mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testParking1
      MYSQL_USER: root
    networks:
      - spring-net



  frontend:
    image: firassaafi/firassaafidocker:frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

  backend:
    image: firassaafi/firassaafidocker:backendfinal8
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: testParking1
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - spring-net


networks:
  spring-net:
    name: spring-net
    driver: bridge
