apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"  # Set the root password
        - name: MYSQL_DATABASE
          value: "testParking1"  # Initial database name
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql  # Default MySQL data directory
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc  # Use a PersistentVolumeClaim
