apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ClusterIP  # Can also be NodePort or LoadBalancer based on your needs
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306  # Port to access the MySQL service
      targetPort: 3306
